/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './features/**/*.{js,ts,jsx,tsx,mdx}',
    './hooks/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
    './store/**/*.{js,ts,jsx,tsx,mdx}',
    './types/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        "border-light": "#e5e7eb",
        "border-dark": "#374151",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        "background-light": "#ffffff",
        "background-dark": "#111827",
        "surface-light": "#f9fafb",
        "surface-dark": "#1f2937",
        "text-main-light": "#1f2937",
        "text-main-dark": "#f3f4f6",
        "text-muted-light": "#6b7280",
        "text-muted-dark": "#9ca3af",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        "accent-red": "#ef4444",
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Balmy Design Tokens
        "white": "var(--color-white)",
        "light-gray": "var(--color-light-gray)",
        "light-gray-2": "var(--color-light-gray-2)",
        "light-gray-3": "var(--color-light-gray-3)",
        "light-gray-4": "var(--color-light-gray-4)",
        "light-gray-5": "var(--color-light-gray-5)",
        "light-gray-6": "var(--color-light-gray-6)",
        "medium-gray": "var(--color-medium-gray)",
        "medium-gray-2": "var(--color-medium-gray-2)",
        "black": "var(--color-black)",
        "black-2": "var(--color-black-2)",
        "black-3": "var(--color-black-3)",
        "black-4": "var(--color-black-4)",
        "dark-gray": "var(--color-dark-gray)",
        "dark-gray-2": "var(--color-dark-gray-2)",
        "dark-gray-3": "var(--color-dark-gray-3)",
        "dark-gray-4": "var(--color-dark-gray-4)",
        "dark-gray-5": "var(--color-dark-gray-5)",
        "dark-blue-gray": "var(--color-dark-blue-gray)",
        "dark-blue-gray-2": "var(--color-dark-blue-gray-2)",
        "red": "var(--color-red)",
        "red-2": "var(--color-red-2)",
        "red-3": "var(--color-red-3)",
        "red-4": "var(--color-red-4)",
        "red-5": "var(--color-red-5)",
        "blue": "var(--color-blue)",
        "blue-2": "var(--color-blue-2)",
        "blue-3": "var(--color-blue-3)",
        "blue-4": "var(--color-blue-4)",
        "blue-5": "var(--color-blue-5)",
        "blue-6": "var(--color-blue-6)",
        "green": "var(--color-green)",
        "green-2": "var(--color-green-2)",
        "green-3": "var(--color-green-3)",
        "orange": "var(--color-orange)",
        "orange-2": "var(--color-orange-2)",
        "yellow": "var(--color-yellow)",
        "purple": "var(--color-purple)",
        "purple-2": "var(--color-purple-2)",
        "purple-3": "var(--color-purple-3)",
        "gold": "var(--color-gold)",
        "report-blue": "#3b82f6",
        "report-border-light": "#d1d5db",
        "stores-primary": "#7c73e6",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
}
